version: '2.2'

services:
    php:
        container_name: container_phpfpm_nginxer
        build:
            context: docker/php8-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ./:/var/www/nginxer
    nginx:
        container_name: container_nginx_nginxer
        build:
            context: docker/nginx
            args:
                MAX_EXECUTION_TIME: ${MAX_EXECUTION_TIME}
        ports:
            - "80:80"
        volumes_from:
            - php
        volumes:
            - "./../docker/volumes/nginxer/logs/nginx/:/var/log/nginx"
